---
# handlers file for cis-ol8-v2.0.0
- name: restart tmpfs
  ansible.builtin.systemd:
    name: tmp.mount
    state: restarted
    enabled: True
    masked: False
    daemon_reload: True

- name: restart aidecheck
  ansible.builtin.systemd:
    name: aidecheck
    enabled: True
    state: restarted

