---

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated)
- name: 1.1.1.1 - Ensure kernel module 'cramfs' is disabled
  lineinfile:
    create: true
    dest: /etc/modprobe.d/cramfs.conf
    regexp: cramfs
    line: install cramfs /bin/true
  tags:
  - 1.1.1.1

- name: 1.1.1.1 - Ensure kernel module 'cramfs' is blacklisted
  lineinfile:
    create: true
    dest: /etc/modprobe.d/cramfs.conf
    regexp: ^blacklist cramfs$
    line: blacklist cramfs
  tags:
  - 1.1.1.1

# 1.1.1.2 Ensure mounting of squashfs filesystems is disabled (Automated)
- name: 1.1.1.2 - Ensure kernel module 'squashfs' is disabled
  lineinfile:
    create: true
    dest: /etc/modprobe.d/squashfs.conf
    regexp: squashfs
    line: install squashfs /bin/true
  tags:
  - 1.1.1.2

- name: 1.1.1.2 - Ensure kernel module 'squashfs' is blacklisted
  lineinfile:
    create: true
    dest: /etc/modprobe.d/squashfs.conf
    regexp: ^blacklist squashfs$
    line: blacklist squashfs
  tags:
  - 1.1.1.2

# 1.1.1.3 Ensure mounting of udf filesystems is disabled (Automated)
- name: 1.1.1.3 - Ensure kernel module 'udf' is disabled
  lineinfile:
    create: true
    dest: /etc/modprobe.d/udf.conf
    regexp: udf
    line: install udf /bin/true
  tags:
  - 1.1.1.3

- name: 1.1.1.3 - Ensure kernel module 'udf' is blacklisted
  lineinfile:
    create: true
    dest: /etc/modprobe.d/udf.conf
    regexp: ^blacklist udf$
    line: blacklist udf
  tags:
  - 1.1.1.3

# 1.1.2.1 Ensure /tmp is a separate partition (Automated)
# 1.1.2.2 Ensure nodev option set on /tmp partition (Automated)
# 1.1.2.3 Ensure noexec option set on /tmp partition (Automated)
# 1.1.2.4 Ensure nosuid option set on /tmp partition (Automated)
- name: 1.1.2.[1-4] - Ensure /tmp is configured
  block:
    - name: Ensure the local-fs directory is created
      ansible.builtin.file:
        path: /etc/systemd/system/local-fs.target.wants
        state: directory
        owner: root
        group: root
        mode: 0755
        setype: etc_t
    - name: 1.1.2.[1-4] - Configure config file for tmpfs
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/local-fs.target.wants/tmp.mount
        block: |
          [Mount]
          What=tmpfs
          Where=/tmp
          Type=tmpfs
          Options=mode=1777,strictatime,noexec,nodev,nosuid
        create: true
        owner: root
        group: root
        mode: 0644
      notify: restart tmpfs
  tags:
  - 1.1.2.1
  - 1.1.2.2
  - 1.1.2.3
  - 1.1.2.4

# 1.1.3.1 Ensure separate partition exists for /var (Automated)
- name: 1.1.3.1 - Report if /var is not on a separate partition
  block:
    - name: 1.1.3.1 - Set/reset mount counter
      ansible.builtin.set_fact:
        mount_count: 0
    - name: 1.1.3.1 - Determine if /var is on a separate partition
      ansible.builtin.set_fact:
         mount_count: "addition{{ mount_count + 1 }}"
         mount_options: "{{ item.options }}"
      when: item.mount == "/var"
      with_items:
        - "{{ ansible_mounts }}"
    - name: 1.1.3.1 - Report to user
      ansible.builtin.debug:
         msg: "FAILED CONTROL: /var is not on a separate partition"
      when: mount_count == 0
      changed_when: true
  tags:
  - 1.1.3.1

# 1.1.3.2 Ensure nodev option set on /var partition (Automated)
- name: 1.1.3.2 - Report if /var does not have nodev set
  ansible.builtin.debug:
    msg: "FAILED CONTROL: /var does not have nodev set"
  when: mount_options is defined and "nodev" not in mount_options and mount_count == 0
  changed_when: true
  tags:
    - 1.1.3.2

# 1.1.3.3 Ensure noexec option set on /var partition (Automated)

# 1.1.3.4 Ensure nosuid option set on /var partition (Automated)


